# BE configuration for Kerberized HDFS access
# Place at: $STARROCKS_HOME/be/conf/be.conf

sys_log_level = INFO
be_port = 9060
be_http_port = 8040
heartbeat_service_port = 9050
brpc_port = 8060
starlet_port = 9070
flush_thread_num_per_store=8
lake_flush_thread_num_per_store=8
load_process_max_memory_limit_percent=50
brpc_socket_max_unwritten_bytes=10737418240
streaming_load_max_mb=204800

# FE address for BE registration (edit_log_port, default 9010)
fe = 192.168.0.211:9010
