[libdefaults]
 dns_lookup_realm = false
 ticket_lifetime = 24h
 renew_lifetime = 7d
 forwardable = true
 rdns = false
 default_realm = ARM.SR.TEST
 dns_lookup_kdc = false

[realms]
 ARM.SR.TEST = {
  kdc = 192.168.0.181:88
  admin_server = 192.168.0.181:749
  default_domain = arm.sr.test
 }

[domain_realm]
 arm-hive = ARM.SR.TEST
 192.168.0.181 = ARM.SR.TEST
 .arm.sr.test = ARM.SR.TEST
 arm.sr.test = ARM.SR.TEST
