[logging]
 default = FILE:/var/log/krb5libs.log
 kdc = FILE:/var/log/krb5kdc.log
 admin_server = FILE:/var/log/kadmind.log

[libdefaults]
 dns_lookup_realm = false
 ticket_lifetime = 24h
 renew_lifetime = 7d
 forwardable = true
 rdns = false
 default_realm = SR.TEST
 default_ccache_name = FILE:/tmp/krb5cc_%{uid}

[realms]
 EXAMPLE.COM = {
  kdc = nfs-server.example.com
  admin_server = nfs-server.example.com
 }
 SR.TEST = {
  kdc = 192.168.0.211:88
  admin_server = 192.168.0.211:749
  default_domain = sr.test
 }

[domain_realm]
 .sr.test = SR.TEST
 sr.test = SR.TEST
 .example.com = EXAMPLE.COM
 example.com = EXAMPLE.COM
