HiveServer {
   com.sun.security.auth.module.Krb5LoginModule required
   useKeyTab=true
   storeKey=true
   useTicketCache=false
   keyTab="/data/deploy/keytabs/hive.service.keytab"
   principal="hive/localhost@SR.TEST"
   debug=true;
};
